# Site settings
title: HOURGLASS CODE
email: contact@hourglasscode.com
description: > # hourglasscode
url: "http://hourglasscode.com" 
baseurl: ""
twitter_username: hourglasscode
github_username:  hourglasscode

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
        block:
            line_numbers: true

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
 - _pages


# emoji:
#  src: "/images/emoji"