# Site settings
title: HOURGLASS CODE
email: p0lym0rph1c@hourglasscode
description: > # hourglasscode
url: "http://hourglasscode.com" # the base hostname & protocol for your site
twitter_username: p0lym0rph1c
github_username:  p0lym0rph1c

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
        block:
            line_numbers: true

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# emoji:
#  src: "/images/emoji"